### ISSUE TITLE
Detect and scan WSL roots and other remotes

### ISSUE THREAD

**Issue by mohitsinghs** [mohitsinghs/vscode-repo#4]
See #2
As of now, WSL2 does not provide any reliable way to retrieve home directories and even if we add them manually, traversal is really slow from Windows.

**Comment by MrLuje** [comment]
I made a few tests on WSL : if the `repo` binary is not found on host side (I explicitly moved it during the test) and I have a `repo` in PATH in WSL filesystem, then everything works fine
https://github.com/mohitsinghs/vscode-repo/blob/b975052cfb122f7f5e9fb8066774e8b34f206433/src/executor.ts#L37-L44

It only shows WSL repositories, but that's what I expect as a WSL vscode user :
* vscode on host shows host repos
* vscode on remote WSL shows WSL repos

Hope it helps :)

**Comment by mohitsinghs** [comment]
That totally makes sense. I think, we should prefer `repo` in PATH over bundled one. That way, it can be used in both environments. What about &mdash;
- exposing a setting to use binary from PATH and using bundled binary as fallback. That should make it at least compatible with WSL for people having `repo` in PATH.
- adding ability to edit `repo` config within VSCode.

On the other hand, combining these two automatically is still a problem which I think we should not solve because these two are different environments and filesystems with very minimal APIs support. Even if I implement that, it will be slow and buggy. The primary reason I created [repo](https://github.com/mohitsinghs/repo) and this extension was speed.

**Comment by MrLuje** [comment]
Yep, looks good to me !
I'm also in favor to not combine host & WSL repositories; as I said I'm fine with only having the repositories from where (host/wsl) vscode has been launched.

An improvement for later on the WSL flow could be to have a vscode command to download the repo unix binary to a known location so we won't have to download it our-self or set the PATH.

**Comment by mohitsinghs** [comment]
I've just published v0.4.0 which includes &mdash;

- `repositories.preferBundled` config, which will look binary in the PATH first when set to `false`.
- `repositories.showInStatusBar` config, which will allows to you to control visibility of current repo in status bar.
- `Repositories: List Repos` command which allow you to search and select repos to jump.
- `Repositories: Edit configuration` command as well as a settings icon in repository view, which allows you to edit current config.
