### ISSUE TITLE
Feature request: open in new window

### ISSUE THREAD

**Issue by will-stone** [mohitsinghs/vscode-repo#6]
Hi 👋 Thanks again for getting this working on a mac 🥳 

Any chance of adding an open-in-new-window button to the repos list?

**Comment by mohitsinghs** [comment]
Yeah, Hopefully by this weekend we will have that too.

**Comment by will-stone** [comment]
Awesome 😎 Thanks!

**Comment by mohitsinghs** [comment]
🎉 v0.5.0 includes ability to open in new window via a context menu.

**Comment by will-stone** [comment]
Nice thanks :)
